spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/cvdb
    username: postgres
    password: password